[package]
name = "libchess-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
libchess = { path = "../libchess" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

